// Renders video.html frame by frame with headless Chromium and encodes an H.264 MP4.
// Soundtrack: music.wav (generated by music.py) is muxed in when present.
// Usage: node render.mjs [out.mp4] [--fps 30] [--stills]
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const out = args.find(a => a.endsWith('.mp4')) || path.join(dir, 'marsh-energy-upstream-ago2026.mp4');
const fps = Number(args[args.indexOf('--fps') + 1]) || 30;
const stills = args.includes('--stills');
const ffmpeg = process.env.FFMPEG || 'ffmpeg';

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
await page.addInitScript(() => { window.__RENDERING__ = true; });
await page.goto('file://' + path.join(dir, 'video.html'));
await page.evaluate(() => document.fonts.ready);
const logo = await page.evaluate(() => window.__logoReady);
console.log(logo ? `logo: ${logo}` : 'logo: none found in assets/, using text wordmark');
const duration = await page.evaluate(() => window.DURATION);

if (stills) {
  for (const t of [3.2, 9.5, 16.5, 23, 30.5, 35.3, 39.8, 44]) {
    await page.evaluate(t => window.render(t), t);
    await page.screenshot({ path: path.join(dir, `still-${String(t).replace('.', '_')}.png`) });
  }
  await browser.close();
  process.exit(0);
}

const music = path.join(dir, 'music.wav');
const audio = fs.existsSync(music)
  ? ['-i', music, '-map', '0:v', '-map', '1:a', '-c:a', 'aac', '-b:a', '192k', '-shortest']
  : [];
const enc = spawn(ffmpeg, [
  '-y', '-f', 'image2pipe', '-framerate', String(fps), '-i', '-', ...audio,
  '-c:v', 'libx264', '-preset', 'slow', '-crf', '17', '-pix_fmt', 'yuv420p',
  '-movflags', '+faststart', out,
], { stdio: ['pipe', 'inherit', 'inherit'] });

const frames = Math.round(duration * fps);
for (let i = 0; i < frames; i++) {
  await page.evaluate(t => window.render(t), i / fps);
  const buf = await page.screenshot({ type: 'jpeg', quality: 95 });
  if (!enc.stdin.write(buf)) await new Promise(r => enc.stdin.once('drain', r));
  if (i % 150 === 0) console.log(`frame ${i}/${frames}`);
}
enc.stdin.end();
await new Promise(r => enc.on('close', r));
await browser.close();
console.log('wrote', out);
